export type ProductCategory = "Cámaras" | "Videoporteros" | "Alarmas y sensores" | "Control de acceso" | "Redes y grabación" | "Otros";

export type Product = {
  code: string;
  name: string;
  brand: string;
  category: ProductCategory;
};

// Catálogo cargado desde la cotización de Electropar Nº 1164279.
// Los precios del documento son costos de proveedor y no se publican en el sitio.
export const products: Product[] = [
  {"code": "117808", "name": "C2 DISTRIBUIDOR DE PISO PRINCIPAL P/ VIDEO PORTERO LINEA MODUM CMD-101BU - COMMAX", "brand": "COMMAX", "category": "Videoporteros"},
  {"code": "117809", "name": "C2 DISTRIBUIDOR DE PISO P/ VIDEO PORTERO LINEA MODUM FULL CMD-404FU - COMMAX", "brand": "COMMAX", "category": "Videoporteros"},
  {"code": "117167", "name": "C2 CITOFONO SECUNDARIO PARA VIDEO PORTERO DP-4VHP - COMMAX", "brand": "COMMAX", "category": "Videoporteros"},
  {"code": "117171", "name": "C2 DISTRIBUIDOR DE PISO P/ VIDEO PORTERO LINEA MODUM CMD-404CFU - COMMAX", "brand": "COMMAX", "category": "Videoporteros"},
  {"code": "117815", "name": "C2 CAMARA DOMO P/ VIDEO PORTERO MODUM VIDEO FULL CAD-I4V7TP - COMMAX", "brand": "COMMAX", "category": "Videoporteros"},
  {"code": "117814", "name": "C2 CAMARA BULLET P/ VIDEO PORTERO MODUM VIDEO FULL CAU-D047TP - COMMAX", "brand": "COMMAX", "category": "Videoporteros"},
  {"code": "117170", "name": "C2 FRENTE VIDEO PORTERO LINEA MODUM CMP-4BCT - COMMAX", "brand": "COMMAX", "category": "Videoporteros"},
  {"code": "133537", "name": "TECLADO PARA(VIDEO PORTERO DS-KD9633-WBE6) DS-KDM9633-FKP - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "124929", "name": "KIT DE VIDEOPORTERO HIBRIDO DS-KIS302-P - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "124928", "name": "KIT DE VIDEOPORTERO IP DS-KIS603-P(C) - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "130173", "name": "MONITOR VIDEOPORTERO ANALOGICO DS-KH2230T - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "124330", "name": "MONITOR VIDEOPORTERO ANDROID 10\" DS-KH9510-WTE1(B) - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "124329", "name": "MONITOR VIDEOPORTERO ANDROID 7\" DS -KH9310-WTE1 - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "130169", "name": "MONITOR VIDEOPORTERO IP DS-KH6100-E1 - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "130170", "name": "MONITOR VIDEOPORTERO IP DS-KH6110-WE1 - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "132597", "name": "TAG DE PROXIMIDAD CS-DL-IC-CPU-R200-GR - EZVIZ", "brand": "EZVIZ", "category": "Control de acceso"},
  {"code": "130166", "name": "KIT DE VIDEOPORTERO ANALOGICO DS-KIS212 - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "129543", "name": "ESTACION DE CONSERJERIA IP DS-KM9503 - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "124328", "name": "FRENTE CALLE ANTIVANDÁLICO DS-KB8113-IME1 - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "133536", "name": "VIDEO PORTERO DS-KD9633-WBE6 - HIKVISION", "brand": "HIKVISION", "category": "Videoporteros"},
  {"code": "130845", "name": "VIDEOPORTERO SMART CS-HP7-R101-1W2TFC - EZVIZ", "brand": "EZVIZ", "category": "Videoporteros"},
  {"code": "121306", "name": "ALARMA CABLEADA DETECTOR DE HUMO DS-PDSMK-4BAR - HIKVISION", "brand": "HIKVISION", "category": "Alarmas y sensores"},
  {"code": "136615", "name": "DVR ACUSENSE 16 CANALES 5MP ALARMA 16/4 iDS-7216HUHI-M2/XT(STD)/4A+16/4A LM - HIKVISION", "brand": "HIKVISION", "category": "Redes y grabación"},
  {"code": "130986", "name": "CAMARA IP DOMO VARIF 4MP DS-2CD3746G2T-IZSY 2.7 A 13.5 MM - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129553", "name": "CAMARA IP DOMO VARIF 4MP DS-2CD3748G2T-LIZSU - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "130988", "name": "CAMARA COLORVU IP PT WIFI 4MP DS-2DE3A400BW-DE/W - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129520", "name": "CAMARA IP ACUSENSE BULLET VARIF 2MP DS-2CD2623G2-IZS - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "134447", "name": "ARCO DETECTOR DE METALES 18 ZONAS ISD-SMG318L - HIKVISION", "brand": "HIKVISION", "category": "Control de acceso"},
  {"code": "133519", "name": "BARRERA BATIENTE INTELIGENTE QR TARJETA RECO FACIAL PARTE MEDIO DS-K3B631TX-M/DPiQL - HIKVISION", "brand": "HIKVISION", "category": "Control de acceso"},
  {"code": "129455", "name": "CAMARA TURBO COLORVU BULLET 2MP DS-2CE10DF0T-PF (2.8MM) - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129468", "name": "CAMARA TURBO COLORVU DOMO 2MP DS-2CE70DF0T-PF(2.8MM) - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129465", "name": "CAMARA TURBO HD BULLET 1MP 720P DS-2CE16C0T-IRPF - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129466", "name": "CAMARA TURBO HD DOMO 1MP DS-2CE56C0T-IRPF - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "121712", "name": "CAMARA TURBO HD BULLET MINI 1MP 720P THC-B110-P 2.8MM - HILOOK", "brand": "HILOOK", "category": "Cámaras"},
  {"code": "120571", "name": "CAMARA TURBO HD BULLET MINI 2MP 1080P THC-B120-PC 2.8MM - HILOOK", "brand": "HILOOK", "category": "Cámaras"},
  {"code": "131286", "name": "CAMARA ACUSENSE IP 4MP BULLET VARIF COLOR NEGRO DS-2CD2646G2-IZS/BLACK - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "132104", "name": "CAMARA ACUSENSE IP 4MP BULLET VARIF DS-2CD2646G2HT-IZS2U/SL(2.8-12 mm) – HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129114", "name": "CAMARA ACUSENSE IP DOMO C/ MIC 6MP DS-2CD2163G2-IU – HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "126536", "name": "CAMARA ACUSENSE IP DOMO MINI 2MP DS-2CD2523G2-I 2.8MM - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "123616", "name": "CAMARA ACUSENSE IP MINI BULLET 6MP DS-2CD2063G2-I - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "130441", "name": "CAMARA ACUSENSE IP TIPO CUBO 2MP DS-2CD2423G2-I – HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "125168", "name": "CAMARA ACUSENSE IP DOMO 4MP DS-2CD1143G2-I - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "126917", "name": "CAMARA ACUSENSE IP DOMO 4MP DS-2CD1143G2-LIU - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "125170", "name": "CAMARA ACUSENSE IP BULLET 4MP C/MIC/ESTROBO DS-2CD2T46G2-ISU/SL - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "124089", "name": "CAMARA ACUSENSE IP BULLET 4MP VARIF DS-2CD2643G2-IZS - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "124927", "name": "CAMARA ACUSENSE IP TURRET 4MP C/ MIC DS-2CD3346G2-ISU/SL - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "120572", "name": "CAMARA TURBO HD BULLET 1MP 720P EXIR 40 THC-B210 2.8MM - HILOOK", "brand": "HILOOK", "category": "Cámaras"},
  {"code": "120567", "name": "CAMARA TURBO HD BULLET VARIF 1MP 720P THC-B310-VF 2.8MM A 12MM - HILOOK", "brand": "HILOOK", "category": "Cámaras"},
  {"code": "120574", "name": "CAMARA TURBO HD BULLET VARIF 2MP 1080P THC-B320-VF 2.8MM A 12MM - HILOOK", "brand": "HILOOK", "category": "Cámaras"},
  {"code": "124031", "name": "CAMARA IP BULLET VARIF 4MP ANPR IDS-2CD7A46G0/P-IZHS - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "133509", "name": "CAMARA IP BULLET 4MP DS-2XC3T46G0H-LISU(PA)(2.8MM) - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "133506", "name": "CAMARA IP BULLET 4MP iDS-2CD7A46G2/P-IZHS(2.8-12mm) - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "133505", "name": "CAMARA IP BULLET 4MP iDS-2CD7A46G2/V-XZHSY(2.8-12mm ) - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "123261", "name": "CAMARA IP DOMO VARIF 2MP IPC-D620H-Z 2.8MM A 12MM - HILOOK", "brand": "HILOOK", "category": "Cámaras"},
  {"code": "124482", "name": "CAMARA IP BULLET VARIF 4MP iDS-2CD7A46G0-IZHSY - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129519", "name": "CAMARA IP ACUSENSE BULLET VARIF 6MP DS-2CD3666G2-IZS - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129579", "name": "CAMARA IP BULLET VARIF LUZ HIBRIDA 2MP DS-2CD1623G2-LIZU - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "125310", "name": "CAMARA IP MOBILE MINI BULLET 2MP DS-2XM6222G1-ID - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "125309", "name": "CAMARA IP MOBILE MINI DOMO 2MP DS-2XM6122G1-ID - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129111", "name": "CAMARA IP MINI BULLET DS-2CD2021G1-I(2.8MM) - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "121728", "name": "CAMARA IP MINI PANOVU + PTZ 2MP 4X PTZ-P332ZI-DE3 - HILOOK", "brand": "HILOOK", "category": "Cámaras"},
  {"code": "122236", "name": "CAMARA IP MINI PANOVU DS-2PT3326IZ-DE3 - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "124660", "name": "CAMARA IP MINI PANOVU+PTZ DS-2PT5326IZ-DE C/ ACC - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "127794", "name": "SENSOR DE TEMPERATURA Y HUMEDAD C/ PANTALLA ZIGBEE SNZB-02D - SONOFF", "brand": "SONOFF", "category": "Alarmas y sensores"},
  {"code": "124336", "name": "ALARMA CABLEADA TECLADO DS-PK1-LRT-HWB - HIKVISION", "brand": "HIKVISION", "category": "Alarmas y sensores"},
  {"code": "134828", "name": "CAMARA IP FISHEYE 12MP IR ANTIVANDALICA C/ MIC DS-2CD63C5G1-IVSUHK – HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "133812", "name": "CAMARA IP FISHEYE 6MP C/MIC Y PARLANTE, MAPA DE CALORDS-2CD6365G1-IVS(1.16mm) (O-STD) - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "124658", "name": "CAMARA IP PTZ 2MP 25X DS-2DF6A225X-AEL C/ ACC - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "129110", "name": "CAMARA IP TURRET COLORVU 4MP DS-2CD1347G2-L - HIKVISION", "brand": "HIKVISION", "category": "Cámaras"},
  {"code": "131451", "name": "SWITCH DE RED 24 PUERTOS GIGA SMART DS-3E1524-EI - HIKVISION", "brand": "HIKVISION", "category": "Redes y grabación"},
  {"code": "110116", "name": "S3 SIRENA 230V 115 dB - SASSIN", "brand": "SASSIN", "category": "Alarmas y sensores"},
];

export const productCategories: ProductCategory[] = [
  "Cámaras",
  "Videoporteros",
  "Alarmas y sensores",
  "Control de acceso",
  "Redes y grabación",
  "Otros",
];
